from __future__ import annotations

import math
from typing import Any

from .base import ConfigTranslator

# GiBUU neutrino flavour_ID (independent of neutrino vs antineutrino, which is
# carried by the sign of process_ID).
FLAVOR_ID = {
    "nue": 1,
    "nuebar": 1,
    "numu": 2,
    "numubar": 2,
    "nutau": 3,
    "nutaubar": 3,
}

# GiBUU process_ID magnitude: CC=2, NC=3. Antineutrinos use the negative value.
PROCESS_ID = {"cc": 2, "nc": 3}

# (protons, neutrons) per nucleus; A = protons + neutrons. Mirrors the mapping
# used by the NuWro translator.
NUCLEUS_COMPOSITION = {
    "Ar40": (18, 22),
    "C12": (6, 6),
    "O16": (8, 8),
    "Fe56": (26, 30),
    "Ca40": (20, 20),
}


class GiBUUTranslator(ConfigTranslator):
    name = "gibuu"

    def translate(self, config: dict[str, Any], task: dict[str, Any]) -> dict[str, Any]:
        flux = config["flux"]
        target = config["target"]
        physics = config["physics"]

        particle = flux["particle"]
        nucleus = target["nucleus"]
        energy_range_gev = [float(flux["emin_gev"]), float(flux["emax_gev"])]
        seed = int(task["seed"])
        event_count = int(task["event_count"])
        current = str(physics.get("current", "cc")).lower()

        protons, neutrons = NUCLEUS_COMPOSITION[nucleus]
        mass_number = protons + neutrons

        flavor_id = FLAVOR_ID[particle]
        process_id = PROCESS_ID[current]
        if particle.endswith("bar"):
            process_id = -process_id

        # Each GiBUU ensemble simulates the whole nucleus but only a fraction of
        # its A nucleons yields an accepted (cross-section-weighted) interaction,
        # so the perturbative event yield is empirically ~A/2 events per ensemble
        # (measured: ~6 events/ensemble on carbon). Size numEnsembles to land
        # near the requested count. The exact number is stochastic and only
        # approximate. GiBUU warns and aborts for numEnsembles < 100 unless the
        # value is given negative (its documented "enforce anyway" override for
        # small runs), so negate small ensemble counts.
        events_per_ensemble = max(1.0, mass_number / 2.0)
        num_ensembles = max(1, math.ceil(event_count / events_per_ensemble))
        if num_ensembles < 100:
            num_ensembles = -num_ensembles

        # Monoenergetic beam at the midpoint of the energy range. Flux-spectrum
        # support is a framework-wide TODO (same limitation as the NuWro path).
        enu_gev = (energy_range_gev[0] + energy_range_gev[1]) / 2.0

        # GiBUU refuses to run unless the jobcard's version matches the code
        # release (e.g. "release2025" -> version=2025).
        version_year = int("".join(c for c in str(task["code_version"]) if c.isdigit()))

        gibuu_jobcard = self._render_jobcard(
            version_year=version_year,
            num_ensembles=num_ensembles,
            proton_number=protons,
            mass_number=mass_number,
            process_id=process_id,
            flavor_id=flavor_id,
            enu_gev=enu_gev,
            seed=seed,
        )

        return {
            "generator": self.name,
            "command": "GiBUU.x",
            "beam_particle": particle,
            "nucleus": nucleus,
            "energy_range_gev": energy_range_gev,
            "number_of_events": event_count,
            "seed": seed,
            "flux_model": flux["type"],
            "mode": physics.get("mode", "inclusive"),
            "code_version": task["code_version"],
            "config_version": task["config_version"],
            "generator_version_id": task.get("generator_version_id"),
            "gibuu_jobcard": gibuu_jobcard,
        }

    @staticmethod
    def _render_jobcard(
        *,
        version_year: int,
        num_ensembles: int,
        proton_number: int,
        mass_number: int,
        process_id: int,
        flavor_id: int,
        enu_gev: float,
        seed: int,
    ) -> str:
        # Fortran namelist jobcard. path_to_input points at the buuinput data
        # shipped in the Docker image; EventFormat=4 selects RootTuple ROOT
        # output. numTimeSteps=0 skips FSI transport for a fast, valid event
        # file (sufficient for the ROOT-output smoke test).
        return f"""! GiBUU neutrino jobcard generated by neutrino-factory
&input
      version         = {version_year}   ! must match the GiBUU code release
      eventtype       = 5          ! neutrino induced
      numEnsembles    = {num_ensembles}
      numTimeSteps    = 0
      num_runs_SameEnergy = 1
      path_to_input   = '/opt/GiBUU/buuinput'
      localEnsemble   = .true.
/
&initRandom
      SEED = {seed}
/
&target
      Z = {proton_number}
      A = {mass_number}
/
&initDensity
      densitySwitch = 2            ! static density (fixed target)
/
&initPauli
      pauliSwitch = 2             ! static Pauli blocking
/
&neutrino_induced
      process_ID     = {process_id}   ! CC=2, NC=3 (negative = antineutrino)
      flavor_ID      = {flavor_id}    ! 1=e, 2=mu, 3=tau
      nuXsectionMode = 6              ! dSigmaMC (fixed energy)
      nuExp          = 0              ! no experimental flux
      includeQE      = .true.
      includeDELTA   = .true.
      includeRES     = .true.
      includeDIS     = .true.
      include1pi     = .true.
      include2p2hQE  = .true.
/
&nl_SigmaMC
      enu = {enu_gev:.4f}
/
&neutrinoAnalysis
      outputEvents = .false.
/
&EventOutput
      WritePerturbativeParticles = .true.
      EventFormat = 4                 ! ROOT (RootTuple)
/
"""
